require("nukevim.plugins-setup")
require("nukevim.core.options")
require("nukevim.core.keymaps")
require("nukevim.core.colorscheme")
require("nukevim.plugins.comment")
require("nukevim.plugins.nvim-tree")
require("nukevim.plugins.lualine")
require("nukevim.plugins.remap")
require("nukevim.plugins.harpoon")
require("nukevim.plugins.undotree")
require("nukevim.plugins.telescope")
require("nukevim.plugins.nvim-cmp")
require("nukevim.plugins.lsp.mason")
require("nukevim.plugins.lsp.rust")
require("nukevim.plugins.crates")
require("nukevim.plugins.lsp.lspsaga")
require("nukevim.plugins.lsp.lspconfig")
require("nukevim.plugins.lsp.null-ls")
require("nukevim.plugins.autopairs")
require("nukevim.plugins.treesitter")
require("nukevim.plugins.rust")
require("nukevim.plugins.typr")
require("nukevim.plugins.gitsigns")
require("nukevim.plugins.discord")
require("nukevim.plugins.alpha")
require("nukevim.plugins.transparent")
require("nukevim.plugins.markdownpreview")
require("nukevim.plugins.wakatime")
require("nukevim.plugins.java")
-- require("nukevim.core.copilot")
require("nukevim.plugins.nvim-notify")
require("nukevim.plugins.obsidian")
require("nukevim.plugins.noice")
require("nukevim.plugins.chatgpt").setup()
require("nukevim.plugins.competitest")
require("nukevim.plugins.dadbod")
require("nukevim.plugins.leetcode").setup()
require("nukevim.plugins.mark")
require("nukevim.plugins.lazygit")
require("nukevim.plugins.gen")



